"use client";
import { useState } from "react";
import type { Project } from "@/content/types";
import { getProjectsState } from "@/lib/content";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { Modal } from "@/components/ui/Modal";
import { GlareHover } from "@/components/react-bits/GlareHover";
import { ClickSpark } from "@/components/react-bits/ClickSpark";

export function Projects({ projects, heading }: { projects: Project[]; heading: { eyebrow?: string; heading?: string } }) {
  const { isEmpty, projects: items } = getProjectsState(projects); const [selected, setSelected] = useState<Project>();
  return <section id="projects" className="px-6 py-24 sm:py-32"><div className="mx-auto max-w-6xl"><SectionHeading {...heading} centered className="mb-14" />
    {isEmpty ? <p className="text-center text-body">No projects are available yet.</p> : <><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{items.map(project => <GlareHover key={project.id} className="rounded-card"><article className="group overflow-hidden rounded-card border border-border bg-bg shadow-card transition duration-200 hover:-translate-y-2 hover:shadow-card-hover"><div className="aspect-[16/10] overflow-hidden bg-surface"><img src={project.thumbnail.src} alt={project.thumbnail.alt} onError={event => { event.currentTarget.src = "/placeholder-project.svg"; }} className="size-full object-cover transition duration-300 group-hover:scale-105 motion-reduce:transition-none" /></div><div className="p-6"><h3 className="text-heading text-xl">{project.title}</h3><p className="text-body mt-3 min-h-20 text-sm leading-6">{project.description}</p><ClickSpark><button onClick={() => setSelected(project)} className="mt-5 text-xs font-extrabold uppercase tracking-wider text-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4">View details →</button></ClickSpark></div></article></GlareHover>)}</div><ClickSpark className="mx-auto mt-10"><a href="/projects" className="flex w-fit rounded-button border border-border px-5 py-3 text-sm font-bold text-primary transition hover:-translate-y-0.5 hover:border-primary">View more projects ↗</a></ClickSpark></>}
  </div>{selected && <Modal open onClose={() => setSelected(undefined)} labelledBy="project-modal-title"><div className="p-7"><div className="flex items-start justify-between gap-4"><h2 id="project-modal-title" className="text-heading-black text-2xl">{selected.title}</h2><button onClick={() => setSelected(undefined)} aria-label="Close project details" className="rounded-button px-2 text-2xl">×</button></div><p className="text-body mt-5 leading-7">{selected.detailBody ?? selected.description}</p>{selected.role && <p className="mt-6 text-sm"><strong>Role:</strong> {selected.role}</p>}{selected.stack?.length && <div className="mt-4 flex flex-wrap gap-2">{selected.stack.map(item => <span key={item} className="rounded-pill bg-surface px-3 py-1 text-xs font-semibold">{item}</span>)}</div>}</div></Modal>}</section>;
}
