import type { SiteContent } from "./types";
import { siteContent } from "./site-content";

const projectCopy: Record<string, { description: string; detailBody: string }> = {
  "brazilian-ecommerce": { description: "Analisis e-commerce yang mengungkap kepuasan pelanggan, performa pengiriman, dan wawasan segmen pelanggan.", detailBody: "Menganalisis data e-commerce Olist Brasil untuk memahami kepuasan pelanggan, performa pengiriman, dan segmen pelanggan. Membangun arsitektur batch ELT dengan HDFS, Hive, dan Apache Spark, lalu menerapkan klasifikasi dan K-Means untuk menghasilkan wawasan bisnis." },
  "city-network-traffic-forecasting": { description: "Sistem peramalan yang memprediksi kecepatan jalan kota hingga 60 menit ke depan.", detailBody: "Membangun pipeline peramalan spasio-temporal multimodal untuk memprediksi kecepatan jalan 20, 40, dan 60 menit ke depan pada 1.260 ruas jalan. Pendekatan ini menggabungkan riwayat kecepatan, fitur jalan dan graf, teks kejadian terstruktur, encoder temporal, serta graph convolution di PyTorch." },
  "ecommerce-delivery-analytics": { description: "Analisis logistik dan model prediksi untuk waktu pengiriman, biaya, penilaian, dan keterlambatan.", detailBody: "Menganalisis data logistik e-commerce untuk menemukan faktor yang memengaruhi durasi pengiriman, biaya, penilaian, dan keterlambatan. Setelah pembersihan dan rekayasa fitur, proyek ini menggunakan fitur berskala dan model regresi linear yang disetel untuk memprediksi waktu serta biaya pengiriman." },
  "ecoevent-finder": { description: "Platform web untuk menemukan, menyimpan, dan mendaftar kegiatan lingkungan.", detailBody: "Membangun platform terpusat agar mahasiswa BINUS dapat menemukan, memfilter, menyimpan, dan mendaftar kegiatan lingkungan. Sistem menggunakan React dan Tailwind CSS, Django REST Framework, penyimpanan MySQL, autentikasi token, dan pembaruan status acara otomatis." },
  "global-electronic-retailers-sales-performance": { description: "Dashboard penjualan interaktif untuk memantau pendapatan, laba, dan biaya lintas pasar, merek, pelanggan, dan kategori produk pada 2016–2021.", detailBody: "Membangun dashboard Tableau interaktif untuk menganalisis performa ritel elektronik global dari 2016 hingga 2021. Dashboard membandingkan tren pendapatan, laba, dan total biaya serta merinci hasil berdasarkan negara, merek, segmen pelanggan, dan kategori produk." },
  "maternal-health-risk": { description: "Sistem machine learning untuk mengklasifikasikan risiko kesehatan ibu dari indikator klinis.", detailBody: "Mengembangkan pipeline klasifikasi risiko kesehatan ibu dengan menggabungkan dua dataset publik dan menyelesaikan data risiko menengah yang ambigu melalui penyaringan berbasis aturan dan jarak Mahalanobis. Setelah penyeimbangan SMOTE, lima model dibandingkan dan Random Forest menghasilkan ROC-AUC terbaik." },
  nutrix: { description: "Aplikasi web berbantuan AI yang mengenali bahan pangan dari foto dan menampilkan informasi gizinya.", detailBody: "Membangun konsep web berbantuan AI yang mengenali buah dan sayur dari foto unggahan serta menampilkan informasi gizi. Prototipe mengintegrasikan API pengenalan gambar Imagga yang menghasilkan label berperingkat beserta skor keyakinannya." },
  "sales-invoice-normalization": { description: "Desain basis data relasional ternormalisasi yang dibuat dari catatan faktur penjualan tidak terstruktur.", detailBody: "Mengubah catatan faktur penjualan dari bentuk tidak ternormalisasi melalui 1NF, 2NF, dan 3NF untuk menghasilkan desain basis data relasional yang terstruktur. Proyek mengidentifikasi anomali insert, update, dan delete, lalu memisahkan entitas dengan relasi primary dan foreign key." },
  payflow: { description: "Aplikasi payroll untuk pemrosesan data, kalkulasi gaji, slip gaji, pelaporan, dan alur pajak pada delapan entitas.", detailBody: "PayFlow HR merupakan aplikasi pengelolaan payroll untuk mendukung operasional penggajian pada 8 PT perusahaan. Aplikasi ini memproses data karyawan dan kehadiran melalui validasi, transformasi, dan agregasi untuk mendukung kalkulasi payroll final, pembuatan slip gaji, pelaporan per divisi, serta perhitungan PPh 21. Sistem juga menghasilkan output yang kompatibel dengan Coretax, dengan kode dan data yang ditampilkan dalam portfolio menggunakan dummy/synthetic data untuk menggantikan seluruh informasi perusahaan dan payroll yang sebenarnya." },
  "shopee-sales-dashboard": { description: "Proyek business intelligence menyeluruh yang mengeksplorasi keterlibatan kategori produk pada data marketplace Shopee.", detailBody: "Shopee Sales Analytics mengevaluasi pola keterlibatan favorit pada kategori produk e-commerce untuk mengidentifikasi kategori dengan engagement yang kuat dan luas. Proyek ini mengintegrasikan data cleaning, validation, transformation, EDA, KPI development, reliability analysis, serta interactive Power BI dashboard dengan DAX untuk menyajikan temuan secara terstruktur dan evidence-based." },
  siaga: { description: "Sistem pendukung keputusan machine learning untuk peringatan banjir dan kekeringan serta alokasi sumber daya di Pantura Jawa.", detailBody: "SIAGA adalah sistem machine learning dan pendukung keputusan untuk peringatan dini serta alokasi sumber daya terhadap risiko banjir dan kekeringan di berbagai kabupaten Pantura Jawa. Proyek mengintegrasikan data iklim, hidrologi, populasi, geografis, infrastruktur, dan satelit serta menggunakan XGBoost terkalibrasi dan optimasi berbasis CVaR." },
  "wiki-next-click": { description: "Sistem prediksi yang memberi peringkat artikel berikutnya yang paling mungkin dalam jalur navigasi Wikipedia.", detailBody: "Membangun sistem prediksi klik berikutnya untuk jalur Wikispeedia dengan merekonstruksi graf tautan artikel dari tangkapan layar menggunakan deteksi tautan biru, Tesseract OCR, dan pencocokan kosakata tertutup. Kandidat diperingkat berdasarkan jarak graf, PageRank, kemiripan TF-IDF, alur, dan kategori." },
};

export const siteContentId: SiteContent = {
  ...siteContent,
  hero: { ...siteContent.hero, role: "Berfokus pada Data Analytics & Data Science", description: "Saya adalah mahasiswa Ilmu Komputer yang berfokus pada analisis data, business intelligence, dan machine learning. Saya senang mengubah data mentah menjadi wawasan bermakna dan membangun solusi berbasis data untuk masalah nyata.", capabilityBadges: ["Analisis Data", "Python • SQL • Power BI", "Machine Learning"] },
  about: { ...siteContent.about, eyebrow: "KENALI", heading: "Tentang Saya", whoAmI: "Saya adalah mahasiswa Ilmu Komputer yang tertarik pada analisis data dan data science. Melalui proyek akademik, organisasi, dan dunia nyata, saya mengolah data untuk menganalisis masalah bisnis, membangun dashboard, dan mengembangkan solusi machine learning.", myApproach: "Saya percaya analisis yang baik dimulai dari pertanyaan yang tepat. Saya menggabungkan Python, SQL, Power BI, dan machine learning untuk mengubah data mentah menjadi wawasan yang jelas dan solusi praktis, dengan tetap memperhatikan kualitas serta konteks data." },
  experience: siteContent.experience.map(entry => ({ ...entry,
    role: ({ "software-engineer-intern": "Magang Software Engineer", "sasc-mentor": "Mentor Beasiswa SASC", "himti-care-manager": "Manajer HIMTI Care", "s-class-participant": "Peserta Program S-Class" } as Record<string, string>)[entry.id] ?? entry.role,
    description: ({ "software-engineer-intern": "Mengembangkan dan memelihara PayFlow HR untuk delapan entitas dalam satu grup perusahaan, mencakup payroll final, dashboard, rekap, slip gaji, PPh 21, dan pemrosesan Coretax.", "sasc-mentor": "Membimbing mahasiswa dalam analisis data, pemrosesan big data, data engineering, pemrograman, dan mata kuliah terkait sambil membantu mengembangkan kemampuan analitis dan teknis.", "himti-care-manager": "Memimpin dan mengoordinasikan lebih dari 50 aktivis mahasiswa serta mengelola perencanaan, pembagian tugas, dan pemantauan progres di berbagai wilayah.", "s-class-participant": "Terpilih dalam S-Class, program intensif SoCS untuk pengembangan teknis dan kompetisi IT; meraih peringkat empat dari 200+ tim pada Ristek UI Datathon bersama SIAGA." } as Record<string, string>)[entry.id] ?? entry.description,
  })),
  marquee: { text: "ANALISIS DATA • BUSINESS INTELLIGENCE • MACHINE LEARNING" },
  hardSkills: siteContent.hardSkills.map(card => ({ ...card, description: ({ "programming-data": "Bahasa dan package utama untuk manipulasi data.", "bi-visualization": "Dashboard interaktif dan pelaporan business intelligence.", "machine-learning": "Pemodelan prediktif, klasifikasi, dan metrik evaluasi.", "database-dev": "Basis data relasional, version control, dan layanan antarmuka." } as Record<string, string>)[card.id] ?? card.description })),
  softSkills: ["Berpikir Analitis", "Pemecahan Masalah", "Komunikasi", "Kolaborasi Tim", "Kepemimpinan", "Manajemen Proyek", "Adaptabilitas", "Mentoring"].map((label, index) => ({ id: siteContent.softSkills[index].id, label })),
  projects: siteContent.projects.map(project => ({ ...project, ...(projectCopy[project.id] ?? {}) })),
  sectionHeadings: {
    experience: { eyebrow: "PENGALAMAN", heading: "Yang Telah Saya Kerjakan" },
    skills: { eyebrow: "KEAHLIAN & TOOLS", heading: "Keahlian & Kemampuan" },
    projects: { eyebrow: "PORTOFOLIO", heading: "Karya Pilihan" },
    contact: { eyebrow: "HUBUNGI SAYA", heading: "Mari Terhubung" },
  },
};
