import type { SiteContent } from "./types";

/**
 * Owner-editable portfolio content. Replace URLs and placeholder assets before
 * publishing; UI components should not contain profile-specific copy.
 */
export const siteContent: SiteContent = {
  hero: {
    name: "Allexa",
    role: "Aspiring Data Analyst & Data Scientist",
    description:
      "I'm a Computer Science student focused on data analytics, business intelligence, and machine learning. I enjoy turning raw data into meaningful insights and building data-driven solutions to solve real-world problems.",
    portrait: {
      src: "/allexandra-profile.jpeg",
      alt: "Portrait of Allexandra Felissa Tioputri",
    },
    capabilityBadges: ["Data Analytics", "Python • SQL • Power BI", "Machine Learning"],
    socialLinks: [
      { platform: "Email", url: "https://mail.google.com/mail/?view=cm&fs=1&to=allexandrafelissa%40gmail.com", iconAlt: "Email Allexa" },
      { platform: "GitHub", url: "https://github.com/allexaFelissa", iconAlt: "Allexa's GitHub profile" },
      { platform: "LinkedIn", url: "https://www.linkedin.com/in/allexandra-felissa-tioputri-ab7b71325", iconAlt: "Allexa's LinkedIn profile" },
      { platform: "Instagram", url: "https://www.instagram.com/allexa.felissa?stkn=MThkNWlrdmhzOGFwag==", iconAlt: "Allexa's Instagram profile" },
    ],
    cvFile: "/CV_Allexandra-Felissa-T.pdf",
  },
  about: {
    eyebrow: "DISCOVER",
    heading: "About Me",
    portrait: {
      src: "/allexandra-profile-about.jpeg",
      alt: "Portrait of Allexandra Felissa Tioputri",
    },
    whoAmI:
      "I'm a Computer Science student passionate about data analytics and data science. Through academic, organizational, and real-world projects, I've worked with data to analyze business problems, build dashboards, and develop machine learning solutions.",
    myApproach:
      "I believe good analysis starts with asking the right questions. I combine Python, SQL, Power BI, and machine learning to turn raw data into clear insights and practical solutions, while paying close attention to data quality and the context behind the numbers.",
    personalDetails: {
      name: "Allexandra Felissa Tioputri",
      placeOfBirth: "Jakarta, Indonesia",
      phone: "+62 896-7770-2873",
      education: "Universitas Bina Nusantara",
    },
  },
  experience: [
    {
      id: "software-engineer-intern",
      year: "Jul 2026 – Sep 2026",
      role: "Software Engineer Intern",
      company: "PT. Satya Ragam Truxpress",
      description:
        "Developed and maintained PayFlow HR for eight entities within the same corporate group, covering final payroll, dashboards, recaps, payslips, PPh 21, and Coretax processing.",
      techTags: ["Data Processing", "Dashboard", "Full-Stack"],
    },
    {
      id: "sasc-mentor",
      year: "Feb 2026 – Present",
      role: "SASC Mentor Scholarship",
      company: "BINUS University",
      description:
        "Mentored students in data analytics, big data processing, data engineering, programming, and related subjects while helping build analytical and technical skills.",
      techTags: ["Mentoring", "Data Analytics", "Programming"],
    },
    {
      id: "himti-care-manager",
      year: "Jan 2026 – Present",
      role: "HIMTI Care Manager",
      company: "HIMTI BINUS University",
      description:
        "Led and coordinated a team of more than 50 student activists, managing planning, task allocation, and progress tracking across multiple regions.",
      techTags: ["Leadership", "Project Management", "Teamwork"],
    },
    {
      id: "s-class-participant",
      year: "Mar 2026 – Present",
      role: "S-Class Program Participant",
      company: "Ureeka, BINUS University",
      description:
        "Selected for S-Class, an intensive SoCS program for technical development and IT competitions; placed fourth among 200+ teams at the Ristek UI Datathon with SIAGA.",
      techTags: ["Data Science", "Machine Learning", "Competition"],
    },
  ],
  marquee: { text: "DATA ANALYTICS • BUSINESS INTELLIGENCE • MACHINE LEARNING" },
  hardSkills: [
    { id: "programming-data", icon: "code", title: "Programming & Data", description: "Core languages and packages for data manipulation.", skills: ["Python", "SQL", "Pandas", "NumPy", "Scikit-learn"] },
    { id: "bi-visualization", icon: "chart", title: "BI & Visualization", description: "Interactive dashboards and business intelligence reporting.", skills: ["Power BI", "DAX", "Power Query", "Tableau", "Matplotlib"] },
    { id: "machine-learning", icon: "spark", title: "Machine Learning", description: "Predictive modeling, classifiers, and evaluation metrics.", skills: ["XGBoost", "Classification", "Model Evaluation"] },
    { id: "database-dev", icon: "database", title: "Database & Dev", description: "Relational stores, version control, and interface services.", skills: ["PostgreSQL", "MySQL", "Git / GitHub", "REST API"] },
  ],
  softSkills: [
    "Analytical Thinking", "Problem Solving", "Communication", "Team Collaboration", "Leadership", "Project Management", "Adaptability", "Mentoring",
  ].map((label) => ({ id: label.toLowerCase().replaceAll(" ", "-"), label })),
  projects: [
    {
      id: "brazilian-ecommerce",
      title: "Brazilian E-Commerce Data Analysis & Business Insights",
      description: "Built a batch analytics pipeline that turns Olist marketplace data into customer, delivery, and segmentation insights.",
      thumbnail: { src: "/projects/brazilian-e-commerce-data-analysis-business-insights.png", alt: "Brazilian e-commerce analysis project cover" },
      detailBody: "Analyzed Olist Brazilian e-commerce data to understand customer satisfaction, delivery performance, and customer segments. Built a batch ELT architecture with HDFS, Hive, and Apache Spark, then applied classification and K-Means clustering to produce business insights.",
      stack: ["Apache Spark", "Hadoop", "HDFS", "Hive", "K-Means"],
      categories: ["Data", "AI"],
      externalUrl: "https://drive.google.com/drive/folders/1B7-rjvNumqJDMibcolQYZdWUhcSqMPNw",
      repositoryUrl: "https://github.com/allexaFelissa/olist-ecommerce-analytics.git",
    },
    {
      id: "city-network-traffic-forecasting",
      title: "City Network Traffic Forecasting",
      description: "Engineered a multimodal forecasting pipeline for road speeds across 1,260 segments, up to 60 minutes ahead.",
      thumbnail: { src: "/projects/city-network-traffic-forecasting.png", alt: "City network traffic forecasting project cover" },
      detailBody: "Built a multimodal spatio-temporal forecasting pipeline to predict road speeds 20, 40, and 60 minutes ahead across 1,260 road segments. The approach combines historical speed windows, static road and graph features, structured event text, a temporal encoder, and graph convolutions in PyTorch.",
      stack: ["PyTorch", "NumPy", "Pandas", "Graph Convolutions"],
      categories: ["AI", "Data"],
      externalUrl: "https://drive.google.com/drive/folders/1WFYj-dDL4nLrDPw-hCWKqg9LQpaEaLVe",
      repositoryUrl: "https://github.com/allexaFelissa/City-Network-Traffic-Forecasting.git",
    },
    {
      id: "ecommerce-delivery-analytics",
      title: "E-Commerce Delivery Analytics & Prediction",
      description: "Developed an analytics and regression workflow to explain and predict delivery time, cost, ratings, and delays.",
      thumbnail: { src: "/projects/e-commerce-delivery-analytics-prediction.png", alt: "E-commerce delivery analytics and prediction project cover" },
      detailBody: "Analyzed an e-commerce logistics dataset to identify factors affecting delivery duration, cost, ratings, and delays. After cleaning and feature engineering, the project used scaled features and tuned linear regression models to forecast delivery time and cost.",
      stack: ["Linear Regression", "StandardScaler", "EDA", "Feature Engineering"],
      categories: ["Data", "AI"],
      externalUrl: "https://drive.google.com/drive/folders/1nolnzVaf80MQGv2n5HBluJ5NffA1j4an",
    },
    {
      id: "ecoevent-finder",
      title: "EcoEvent Finder",
      description: "Built a full-stack event platform with discovery, filtering, bookmarks, registration, and automated status updates.",
      thumbnail: { src: "/projects/ecoevent-finder.png", alt: "EcoEvent Finder project cover" },
      detailBody: "Built a centralized web platform where BINUS students can discover, filter, bookmark, and register for environmental events. The system uses React and Tailwind CSS on the frontend, Django REST Framework on the backend, MySQL storage, token authentication, and automatic event-status updates.",
      stack: ["React.js", "Tailwind CSS", "Django REST Framework", "MySQL"],
      categories: ["Web"],
      externalUrl: "https://drive.google.com/drive/folders/1ArnWNF1pz582UBU7jaUABh9sMsIoVSRH",
      repositoryUrl: "https://github.com/Shanshine12/eco-event-finder-web-app.git",
      demoUrl: "https://eco-event-finder-web-app.vercel.app/",
    },
    {
      id: "global-electronic-retailers-sales-performance",
      title: "Global Electronic Retailers Sales Performance",
      description: "Designed a Tableau dashboard that reveals revenue, profit, and cost drivers across markets, brands, and product categories.",
      thumbnail: { src: "/projects/global-electronic-retailers-sales-performance.png", alt: "Global Electronic Retailers Sales Performance project cover" },
      detailBody: "Built an interactive Tableau dashboard to analyze global electronics retail performance from 2016 to 2021. The dashboard compares revenue, profit, and total cost trends while breaking down results by country, leading brands, customer segments, and product categories to highlight the strongest contributors to business performance.",
      stack: ["Tableau", "Sales Analytics", "Data Visualization", "Dashboard Design"],
      categories: ["Data"],
      demoUrl: "https://public.tableau.com/app/profile/shanaa.salsabil/viz/GlobalElectronicRetailersSalesPerformanceDashboard2016-2021/Dashboard5",
    },
    {
      id: "maternal-health-risk",
      title: "Maternal Health Risk Classification with Machine Learning",
      description: "Built and evaluated a risk-classification pipeline using clinical indicators, data integration, SMOTE, and five competing models.",
      thumbnail: { src: "/projects/maternal-health-risk-classification-machine-learning.png", alt: "Maternal health risk classification project cover" },
      detailBody: "Developed a maternal health risk classification pipeline by integrating two public datasets and resolving ambiguous mid-risk records with rule-based screening and Mahalanobis distance. After SMOTE balancing, five models were compared, with Random Forest producing the strongest reported ROC-AUC.",
      stack: ["Random Forest", "XGBoost", "SMOTE", "Mahalanobis Distance"],
      categories: ["AI", "Data"],
      externalUrl: "https://drive.google.com/drive/folders/1_nTdboEhn12mRiI-NiI33_PcDlxeMlNI",
    },
    {
      id: "nutrix",
      title: "Nutrix",
      description: "Prototyped an AI-assisted experience that recognizes produce from photos and returns ranked labels with nutrition facts.",
      thumbnail: { src: "/projects/nutrix.png", alt: "Nutrix project cover" },
      detailBody: "Built an AI-assisted web concept that identifies fruits and vegetables from uploaded photos and returns nutrition facts. The prototype integrates the Imagga image-recognition API, which uses pretrained CNN-based recognition and returns ranked labels with confidence scores.",
      stack: ["Imagga API", "CNN", "REST API", "Figma"],
      categories: ["AI", "Web"],
      externalUrl: "https://drive.google.com/drive/folders/1E2ARwGkEcFdWzYP9w7tXkjzkRrfDpaDx",
    },
    {
      id: "sales-invoice-normalization",
      title: "Sales Invoice Database Design & Normalization",
      description: "Converted unstructured invoice records into a 3NF relational design that resolves insert, update, and delete anomalies.",
      thumbnail: { src: "/projects/sales-invoice-database-design-normalization.png", alt: "Sales invoice database design and normalization project cover" },
      detailBody: "Transformed sales invoice records from unnormalized form through 1NF, 2NF, and 3NF to produce a structured relational database design. The project identified insert, update, and delete anomalies, then separated entities with primary and foreign-key relationships.",
      stack: ["Database Design", "Normalization", "1NF-3NF", "Excel"],
      categories: ["Data"],
      externalUrl: "https://drive.google.com/drive/folders/1QtwGTDyMfee63iJiH1NlDCf6y61JG9DQ",
    },
    {
      id: "payflow",
      title: "PayFlow HR: Payroll Management System",
      description: "Commissioned by PT Satya Ragam Truxpress and used to run payroll, payslips, reporting, and tax workflows across eight entities.",
      thumbnail: { src: "/projects/payflow.png", alt: "PayFlow HR payroll management system project cover" },
      detailBody: "Commissioned by PT Satya Ragam Truxpress, PayFlow HR is used in live payroll operations across eight entities in the same corporate group. It validates, transforms, and aggregates employee and attendance data for final payroll, payslips, division reporting, PPh 21 calculations, and Coretax-compatible outputs. The public demo uses synthetic data to protect company and payroll information.",
      stack: ["Laravel", "React", "PostgreSQL", "REST API", "Tailwind CSS", "Git", "PHP"],
      categories: ["Web", "Data"],
      repositoryUrl: "https://github.com/allexaFelissa/payFlow-demo.git",
    },
    {
      id: "shopee-sales-dashboard",
      title: "Shopee Sales Analytics",
      description: "Delivered an end-to-end BI workflow that turns Shopee marketplace data into defensible category-engagement insights.",
      thumbnail: { src: "/projects/shopee-sales-dashboard.png", alt: "Shopee Sales Dashboard project cover" },
      detailBody: "Shopee Sales Analytics evaluates favorite engagement patterns across e-commerce product categories to identify categories with strong and widespread engagement. The project integrates data cleaning, validation, transformation, EDA, KPI development, reliability analysis, and an interactive Power BI dashboard with DAX to deliver structured, evidence-based insights.",
      stack: ["Python", "SQL", "Pandas", "Power BI", "DAX", "Power Query", "Matplotlib"],
      categories: ["Data"],
      externalUrl: "https://drive.google.com/drive/folders/1g0duot8RHHL51TwSvlld5R4u3iPb5IIh?usp=sharing",
      repositoryUrl: "https://github.com/allexaFelissa/shopee-sales.git",
    },
    {
      id: "siaga",
      title: "SIAGA: Multi-Hazard Early Warning & Resource Allocation",
      description: "Placed 4th among 200+ teams at RISTEK UI Datathon 2026 with a disaster-risk and resource-allocation system for Northern Java.",
      thumbnail: { src: "/projects/siaga.png", alt: "SIAGA project cover" },
      detailBody: "SIAGA earned 4th place among 200+ teams at RISTEK UI Datathon 2026, one of Indonesia's largest data competitions. The system supports early warning and resource allocation for flood and drought risks across Northern Java by integrating climate, hydrology, population, geographic, infrastructure, and satellite data. It combines calibrated XGBoost risk models with CVaR-based optimization for limited-resource planning under high-risk scenarios.",
      stack: ["Python", "XGBoost", "Scikit-learn", "GloFAS", "ERA5", "WorldPop", "OpenStreetMap", "Sentinel-1", "CVaR"],
      categories: ["AI", "Data"],
      externalUrl: "https://drive.google.com/drive/folders/17j7aW-oIbz7_Q-usaRaL8boEbt52mQxG",
      repositoryUrl: "https://github.com/ethannchrstian/Siaga.git",
    },
    {
      id: "wiki-next-click",
      title: "Wiki Article Next Click Prediction",
      description: "Built a graph and OCR ranking system that predicts the most likely next article in a Wikipedia navigation path.",
      thumbnail: { src: "/projects/wiki-article-next-click-prediction.png", alt: "Wiki Article Next Click Prediction project cover" },
      detailBody: "Built a next-click prediction system for Wikispeedia navigation paths by reconstructing the article link graph from screenshots using blue-link detection, Tesseract OCR, and closed-vocabulary matching. Candidates were ranked using graph distance, PageRank, TF-IDF similarity, flow, and category signals.",
      stack: ["Tesseract OCR", "NetworkX", "TF-IDF", "PageRank", "RapidFuzz"],
      categories: ["AI", "Data"],
      externalUrl: "https://drive.google.com/drive/folders/1Ao3zxFAr_pRDxmIlpLXwubrbBPvoHHTS",
      repositoryUrl: "https://github.com/allexaFelissa/Wiki-Article-Next-Click-Prediction.git",
    },
  ],
  sectionHeadings: {
    experience: { eyebrow: "EXPERIENCE", heading: "What I've Done" },
    skills: { eyebrow: "SKILLS & TOOLS", heading: "Skills & Expertise" },
    projects: { eyebrow: "PORTFOLIO", heading: "Selected Works" },
    contact: { eyebrow: "GET IN TOUCH", heading: "Contact Me" },
  },
};

export default siteContent;
