"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Modal } from "@/components/ui/Modal";
import { StatusDot } from "@/components/ui/StatusDot";
import { isValidChatInput } from "@/lib/validation";
type Message = { role: "visitor"|"assistant"; text: string; time: string };
const stamp = () => new Intl.DateTimeFormat("en", { hour: "2-digit", minute: "2-digit" }).format(new Date());
export function AiAssistantModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [messages, setMessages] = useState<Message[]>([]); const [question, setQuestion] = useState(""); const [typing, setTyping] = useState(false); const bottom = useRef<HTMLDivElement>(null);
  useEffect(() => { if (open && !messages.length) setMessages([{ role: "assistant", text: "Hi — ask me about Allexa's experience, skills, or projects.", time: stamp() }]); }, [open, messages.length]);
  useEffect(() => { if (typeof bottom.current?.scrollIntoView === "function") bottom.current.scrollIntoView(); }, [messages, typing]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!isValidChatInput(question)) return; const text = question.trim(); const visitor: Message = { role: "visitor", text, time: stamp() }; setMessages(current => [...current, visitor]); setQuestion(""); setTyping(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ question: text, history: messages }) }); const data = await response.json(); if (!response.ok) throw new Error(); setMessages(current => [...current, { role: "assistant", text: data.answer, time: stamp() }]); } catch { setMessages(current => [...current, { role: "assistant", text: "I couldn't answer just now. Please try again.", time: stamp() }]); } finally { setTyping(false); } }
  return <Modal open={open} onClose={onClose} labelledBy="assistant-title" variant="bottom-sheet"><div className="flex h-[min(680px,90vh)] flex-col"><header className="flex items-center justify-between border-b border-border p-5"><div><div className="flex items-center gap-2"><StatusDot /><h2 id="assistant-title" className="text-heading">Portfolio assistant</h2></div><p className="mt-1 text-xs text-muted">Answers from the portfolio only</p></div><button onClick={onClose} aria-label="Close assistant" className="rounded-button p-2 text-xl focus-visible:outline focus-visible:outline-2">×</button></header><div className="flex-1 space-y-4 overflow-y-auto bg-surface p-5" aria-live="polite">{messages.map((message,index) => <div key={index} className={`flex ${message.role === "visitor" ? "justify-end" : "justify-start"}`}><div className={`max-w-[85%] rounded-bubble px-4 py-3 text-sm ${message.role === "visitor" ? "bg-primary text-bg" : "border border-border bg-bg text-primary"}`}><p>{message.text}</p><time className="mt-1 block text-[10px] opacity-60">{message.time}</time></div></div>)}{typing && <div aria-label="Assistant is typing" className="w-fit rounded-bubble border border-border bg-bg px-4 py-3 text-muted">•••</div>}<div ref={bottom} /></div><form onSubmit={submit} className="flex gap-2 border-t border-border p-4"><input aria-label="Ask a question" maxLength={1000} value={question} onChange={e => setQuestion(e.target.value)} className="min-w-0 flex-1 rounded-pill border border-border bg-bg px-4 py-3 text-sm outline-none focus:border-primary" placeholder="Ask about this portfolio…" /><button disabled={typing} className="rounded-pill bg-primary px-5 text-sm font-bold text-bg disabled:opacity-50">Send</button></form></div></Modal>;
}
